version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: NginxDockerfile
    ports:
      - "80:80"
      - "443:443"
    network_mode: "host"
    restart: always
    volumes:
      # Mount the whole `/https/` folder. 
      # Used to generate and hold certificates.
      #  -> `/https/webroot/` is used to serve static content for the challenge during cert creation
      #  -> `/https/sslcerts/` is where the certificates are stored
      - "/https/:/https/"
