version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: NginxDockerfile
    ports:
      - "80:80"
      - "443:443"
    network_mode: "host"
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt/:ro"
